# Generated by Django 4.2.4 on 2023-09-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0006_alter_students_s_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='S_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
